#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width	1
bspc config window_gap		5

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true

# Autostart

feh --bg-max $HOME/Pictures/Wallpaper3_modified.jpg 	  # Wallpaper
picom --experimental-backends &				  # Compositor
$HOME/.config/polybar/launch.sh				  # Polybar
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 & # Authenticator
eww daemon						  # EWW
